name: Deploy Django to Azure Container Apps

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        env:
          ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
          IMAGE_NAME: acrsample
          IMAGE_TAG: ${{ github.sha }}
        run: script/docker-build

      - name: Push Docker image to ACR
        env:
          ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: script/docker-push

      - name: Log in to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        env:
          ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.sha }}
          RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          CONTAINER_APP_NAME: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
        run: |
          az containerapp update \
            --name ${CONTAINER_APP_NAME} \
            --resource-group ${RESOURCE_GROUP} \
            --image ${ACR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
